version: '3'
services:
  nestjs-app:
    depends_on:
      - mongdb-utn
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${PORT}
    env_file:
      - .env

  mongdb-utn:
    image: mongo
    ports:
      - 27017:27017
